### ISSUE TITLE
Feature request: RIC codes

### ISSUE THREAD

**Issue by hoenie-ams** [CharlesCara/DatastreamDSWS2R#1]
Hi Charles, would it please be possible to add an option to use RIC codes instead of mnemonics? In Excel there is an checkbox for this. Perhaps it's an idea to add an parameter 'RIC = TRUE' to the function? Thanks!

**Comment by CharlesCara** [comment]
Hi Hoenie.  You can do this by putting the RIC code in square brackets eg
`mydsws$snapshotRequest(instrument = "<VOD.L>", datatype = "NAME", requestDate = Sys.Date())`

Faster performance can be acheived by wrapping the code in the SYM# function.
`mydsws$snapshotRequest(instrument = "SYM#(VOD.L,RIC)", datatype = "NAME", requestDate = Sys.Date())`

**Comment by ghost** [comment]
I have tried wrapping the RIC in the <> brackets as you suggest, but it appears that RICs with lower case letters are converted to upper case in the request, which then returns no data as RICs are case sensitive.  For example: <WAFGn.DE>: 

JSON request to DSWS server is:

{"DataRequest":{"DataTypes":[{"Properties":{},"Value":["ISIN"]},{"Properties":{},"Value":["MED#(X(VA)~U$, -1Y, 0D)"]}],"Date":{"End":["2019-06-07"],"Frequency":["D"],"Kind":[0],"Start":["2019-06-07"]},"Instrument":{"Properties":{},"Value":["<WAFGN.DE>"]},"Tag":{}},"Properties":{"Properties":{}},"TokenValue":["xxx"]}

**Comment by CharlesCara** [comment]
Fixed in version 1.6.5
