### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by miguellacerda** [CharlesCara/DatastreamDSWS2R#11]
I find that my requests (using timeSeriesRequest) sometimes timeout, particular when I am requesting many, long time series. This is frustrating when trying to set up automated pipelines, as sometimes it works and sometimes it doesn't. Is there a way to set the timeout value (longer than 30s)? If not, I would like to request that this please be added as an optional parameter.

**Comment by CharlesCara** [comment]
I have revised the timeout to 300s.
