### ISSUE TITLE
Maximum number of instruments

### ISSUE THREAD

**Issue by miguellacerda** [CharlesCara/DatastreamDSWS2R#12]
Is there a reason that the maximum number of instruments that can be queried at one time is set to 20 (both in snapshotRequest and timeSeriesRequest)? This is quite restrictive and I typically have to call timeSeriesRequest repeatedly within a loop to get all the data that I need.

**Comment by CharlesCara** [comment]
The Datastream DSWS service puts a limit on the number of series that can be requested at the same time.  Once you set the chunk size, you can make a single timeSeriesRequest and this package will do the chunking for you.  You do not need to loop.

**Comment by aganchev1** [comment]
Even though I can call multiple series via snapshotRequest, I get the same issue where I cannot call more than 20 id's at one time via timeSeriesRequest as I get the below error:
```r
Error requesting data.  HTTP message was: Server error : Internal Server Error : Server error: (500) Internal Server Error
```

**Comment by CharlesCara** [comment]
This is an error being generated by DSWS, not by the package.  Have you tried setting a lower chunk limit?
options(Datastream.ChunkLimit = 20L)

**Comment by aganchev1** [comment]
yes that fixed it, thanks!
