### ISSUE TITLE
Installation error DatastreamDSWS2R in R / There is no package called 'DatastreamDSWS2R' 

### ISSUE THREAD

**Issue by adragosch** [CharlesCara/DatastreamDSWS2R#14]
Hello, I have tried to install the DatastreamDSWS2R package by downloading the zip file first and then calling install("Myfilepath/DatastreamDSWS2R-master"). When I do this, I get the following error (see screenshot). It says there is no package called 'DatastreamDSWS2R'. Could you help me out with this, please? Any help would be appreciated.

![R_Error](https://user-images.githubusercontent.com/56151516/66191678-2c552480-e68f-11e9-8122-ec26a8fef965.PNG)

PS: I wasn't able to install the package via the devtools function "install_github(CharlesCara/DatastreamDSWS2R)" either.

**Comment by CharlesCara** [comment]
The 'system command error' indicates that this is likely a configuration issue with your machine, rather than a DatastreamDSWS2R problem.  See https://github.com/r-lib/devtools/issues/2031 or try a google search on 'R package install system command error'
