### ISSUE TITLE
snapshotRequest with expression doesn't return the instrument in the data frame

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [CharlesCara/DatastreamDSWS2R#16]
I have used this code:

`myData <- mydsws$snapshotRequest(instrument = c("ABF","RIO","WPP"),
                               expression = "PCH#(XXXX,3M)",
                               requestDate = "0D")
`
The returned data does't have instruments.

Instrument	X
<dbl>	<dbl>
NA	-7.48
NA	-10.11
NA	1.88

**Comment by CharlesCara** [comment]
Can you check that you have upgraded to Version: 1.6.2.

**Comment by jirapongse-refinitiv** [comment]
> Can you check that you have upgraded to Version: 1.6.2.

Thank you so much. 1.6.2 returns the instruments.
