### ISSUE TITLE
DS.USERSTATS only returns the User field.

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [CharlesCara/DatastreamDSWS2R#17]
I have used this code:
`
myData <- mydsws$snapshotRequest(instrument = "STATS",
                               datatype = c("DS.USERSTATS"),                           
                               requestDate = Sys.Date())
`

The returned data is:

Instrument	User
<chr>	<chr>
STATS	ZEIK339

**Comment by CharlesCara** [comment]
Looks like a duplicate of #16.
