### ISSUE TITLE
timeSeriesListRequest with LFTSE100 returns Server error: (500) Internal Server Error

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [CharlesCara/DatastreamDSWS2R#18]
I have tested timeSeriesListRequest with LFTSE100.

`
xtsData <- mydsws$timeSeriesListRequest(instrument = "LFTSE100",
                       datatype = "P",
                       startDate = "-30D",
                       endDate = "-0D",
                       frequency = "D")
`

It returns:
Error requesting data.  HTTP message was: Server error : Internal Server Error : Server error: (500) Internal Server Error
​

**Comment by CharlesCara** [comment]
This looks like a error that is internal to the refinitiv DSWS server.  The command is working for me.  Is it recurring?

**Comment by jirapongse-refinitiv** [comment]
Thank you so much for the response. After using a proxy, I found this error.

`
   {
        "Code": "ResponseTooLarge",
        "Message": "This GetDataBundle request contains too many sub-requests (101). Maximum permitted number of sub-requests is 20.",
        "SubCode": "TotalRequests"
    }
`

It could be a limitation of my account.

**Comment by CharlesCara** [comment]
Add this line to your .RProfile file.
```
options(Datastream.ChunkLimit = 20L)
```

**Comment by jirapongse-refinitiv** [comment]
> options(Datastream.ChunkLimit = 20L)

Thank you so much. It works now.
