### ISSUE TITLE
timeSeriesRequest returns NAs for certain RICs

### ISSUE THREAD

**Issue by miguellacerda** [CharlesCara/DatastreamDSWS2R#21]
There seems to be a problem extracting data with timeSeriesRequest for certain RICs. For example, consider Naspers (mnemonic = R:NPNJ and RIC = NPNJn.J) on the Johannesburg Stock Exchange (JSE). Requesting the price series using the RIC returns NAs:

`mydsws$timeSeriesRequest(instrument = '<NPNJn.J>', datatype = 'P', startDate = '-1Y', endDate = '0D') `

But requesting the same data using the Reuters mnemonic does work:

`mydsws$timeSeriesRequest(instrument = 'R:NPNJ', datatype = 'P', startDate = '-1Y', endDate = '0D') `

I can, however, get the price data by RIC using snapshotRequest:

`mydsws$snapshotRequest(instrument = '<NPNJn.J>', datatype = 'P', requestDate = '0D') # works!`

I have observed the same behaviour for Naspers' spin-off company Prosus (mnemonic = R:PRXJ and RIC = PRXJn.J). 

It might be worth noting that the mnemonics and RICs for stocks on the JSE are typically of the form R:---J and ---J.J, respectively. Naspers and Prosus are exceptions in that the RIC is of the form ---Jn.J (note the little "n"). These are the only two stocks that I have found where timeSeriesRequest returns NAs if you use their RICs, and it so happens that their RICs are unusual.

**Comment by CharlesCara** [comment]
The two RICs that do not work have lower case characters in them. Version 1.6.3 (released on Tuesday) now handles these.  Is this a bug relating to version 1.6.3?  If not, then could you try upgrading?

**Comment by miguellacerda** [comment]
Yup - all fixed in version 1.6.3 (though the package help file claims it's version 1.6.5!).
