### ISSUE TITLE
No data returned for certain tickers

### ISSUE THREAD

**Issue by pat-alt** [CharlesCara/DatastreamDSWS2R#22]
For certain tickers `timeSeriesRequest` returns no data, even though when searching for the data on Excel I can see it is available. For example, 

```mydsws = dsws$new()
raw_output = mydsws$timeSeriesRequest(
      instrument = "USAUD3F",
      datatype = "EB",
      startDate = "1999-12-31",
      endDate = Sys.Date()-1,
      frequency = "D"
) 
length(raw_output)
```
returns `0`. Similarly, for other forward exchange rates no data is returned. With the deprecated [package](https://github.com/fcocquemas/rdatastream) it used to work. Any idea what the issue may be?

Many thanks!

**Comment by CharlesCara** [comment]
I suspect this might be a data licence permissioning problem.  

You can see what Datastream returned in detail by running `mydsws$getDataResponse()` after a request.  In my case I get an Access Denied error, since WMR tightened up API access to its data about 3 months, and we no longer have a subscription.

```
$DataResponses
$DataResponses[[1]]
$DataResponses[[1]]$AdditionalResponses
NULL

$DataResponses[[1]]$DataTypeNames
NULL

$DataResponses[[1]]$DataTypeValues
$DataResponses[[1]]$DataTypeValues[[1]]
$DataResponses[[1]]$DataTypeValues[[1]]$DataType
[1] ""

$DataResponses[[1]]$DataTypeValues[[1]]$SymbolValues
$DataResponses[[1]]$DataTypeValues[[1]]$SymbolValues[[1]]
$DataResponses[[1]]$DataTypeValues[[1]]$SymbolValues[[1]]$Currency
NULL

$DataResponses[[1]]$DataTypeValues[[1]]$SymbolValues[[1]]$Symbol
[1] "USAUD3F"

$DataResponses[[1]]$DataTypeValues[[1]]$SymbolValues[[1]]$Type
[1] 0

$DataResponses[[1]]$DataTypeValues[[1]]$SymbolValues[[1]]$Value
[1] "$$ER: E100,ACCESS DENIED "





$DataResponses[[1]]$Dates
NULL

$DataResponses[[1]]$SymbolNames
NULL

$DataResponses[[1]]$Tag
[1] ""



$Properties
NULL
```
