### ISSUE TITLE
Logging with token only (without credentials) not possible

### ISSUE THREAD

**Issue by vh-d** [CharlesCara/DatastreamDSWS2R#28]
I am in a corporate environment where users are not supposed to user credentials directly, but only with a token given from local server.

Currently, DatastreamDSWS2R requires credentials eventhough Refinitiv API does not. 

A potential workaround may be to give it some fake credentials.

I am willing to make a PR with proper handling of the case, but it may require some refactoring of the code base, I assume.

**Comment by CharlesCara** [comment]
Hi  Yes, please make a PR with the code change.  
You can initialise the instance with a token provided by the API ie
```
mydsws <- dsws$new(token = list(TokenValue= "XXX", TokenExpiry= as.Date("YYYY-MM-DD"))
```
But it seems like you want to do something different.

Take a look at the methods initialize, .loadToken, .tokenExpired, .makeRequest in classConstructor.R which handle the authentication and connection with the Refinitiv server.

**Comment by vh-d** [comment]
```
mydsws <- dsws$new(token = list(TokenValue= "XXX", TokenExpiry= as.Date("YYYY-MM-DD"))
```

Yes, that is exactly what I want to do. But the `initialize()` method wont let me:

```
if(username != ""){
    .self$username <<- username
  } else if(Sys.getenv("DatastreamUsername") != ""){
    .self$username <<- Sys.getenv("DatastreamUsername")
  } else if(!is.null(options()$Datastream.Username)){
    .self$username <<- options()$Datastream.Username
  } else {
    stop("Either username must be specified or it must be set via options(\"Datastream.Username\", \"Myusername\"")
  }
```

I suppose I can fake it with some dummy credentials, but I was not sure it won't bite me later.

**Comment by vh-d** [comment]
I can see that the token is renewed whenever it expires.
```
  if(.self$.tokenExpired()){
    .self$.loadToken()
  }
```
so my dummy password would make it fail.

One elegant solution (without major changes to the code) to this would be a new optional argument to the constructor function letting the user to pass a function that would renew the token. The user would have to provide either credentials or this token-generating function.

**Comment by vh-d** [comment]
I will try to come back with a PR as minimalist as possible.

**Comment by CharlesCara** [comment]
Yes, I see that would be a good solution.

**Comment by CharlesCara** [comment]
You should also change the logic in initialise so that if token is passed then it does not need to check for username and password

**Comment by CharlesCara** [comment]
In Version 1.17.1 I have added a callback function that can be used as the source of the access token.  Thinking through the logic there is the question about how this function will refresh the token, but I have left that for the callback function to solve.
