### ISSUE TITLE
Datastream QTEALL

### ISSUE THREAD

**Issue by FreekOlivier** [CharlesCara/DatastreamDSWS2R#29]
Hi Charles,

I noticed you make use of QTEALL, a datatype not many know! Since it returns CD01, MN01, MJ01, etc, I was wondering if you can alter the output of this type?

Since I also need the listing DATE of each of these associated stocks

Hope you can help :)

(I am doing research on reverse cross listing for my university)

**Comment by CharlesCara** [comment]
No the output cannot be changed - we are just passing on the output of request as provided by the DSWS server.  

I think you can get the listing date of each stock using the BDATE datatype, once you have the code of each listing.
