### ISSUE TITLE
INF string not correctly parsed

### ISSUE THREAD

**Issue by tega** [CharlesCara/DatastreamDSWS2R#3]
The "INF" string such as the mnemonic of INFORMA is incorrectly converted to Inf.
Example:

    result.df <- mydsws$listRequest(instrument="INF", datatype=c("NAME","MNEM","ISIN","RIC"), requestDate="-0D")
    
    result.df

    >  Instrument    NAME MNEM         ISIN   RIC
    >1        Inf INFORMA  Inf GB00BMJ6DW54 INF.L

**Comment by CharlesCara** [comment]
Have changed the snapshot request to use the explicit type returned by DSWS, as now documented.   Change made in version 1.2.13
