### ISSUE TITLE
Undeclared variables during Cran Check

### ISSUE THREAD

**Issue by GreenGrassBlueOcean** [CharlesCara/DatastreamDSWS2R#30]
Dear Charles,

Thanks a lot for your Github project. I have been using it for a while and I am very satisfied with the performance. As I wanted to check the package I did a cran check with it on rstudio. I had to make a number of textual changes to the documentation, Desription file and  datafiles in order to get it running. You can find these here: https://github.com/GreenGrassBlueOcean/DatastreamDSWS2R
For example the tests can not be run because they require authentication. This can be solved at a later stage by maybe adding some data for tests and excluding some other tests from the package.

However when the Cran checks the r code itself it gave the following warning:
```

> checking R code for possible problems ... NOTE
  .getJSONValue: no visible global function definition for
    '.convert_JSON_Boolean'
  UCTSAppend: no visible global function definition for
    'make.index.unique'
  staticListRequestSet: no visible binding for global variable
    'iExpression'
  staticRequestSet: no visible binding for global variable 'iExpression'
  Undefined global functions or variables:
    .convert_JSON_Boolean iExpression make.index.unique
```
When I then check the code it looks like these function are not present at all in the package?
Could you please help me with this?

**Comment by CharlesCara** [comment]
I have taken a look and fixed these issues.  

Do you think you could make a pull request for the changes that you have made and then I will merge my changes in.

**Comment by GreenGrassBlueOcean** [comment]
pls see pull request
