### ISSUE TITLE
timezone of DatastreamDSWS2R:::.convert_JSON_Datetime

### ISSUE THREAD

**Issue by GreenGrassBlueOcean** [CharlesCara/DatastreamDSWS2R#32]
Hello Charles,

I am still going through the tests and I am stuck on the first test in test-common.R:

```
 jsonDate <- "/Date(1449218172199)/"
 rDate <- DatastreamDSWS2R:::.convert_JSON_Datetime(jsonDate)
 expect_equal(rDate, as.POSIXlt("2015-12-04 08:36:12 GMT"), tolerance = 0.5)
 ```
this test fails on my computer that runs on CET (and not GMT) .
The values on my PC for 
rDate is  
```
> rDate
[1] "2015-12-04 09:36:12 CET"
```
the test result shows:
```
`rDate` not equal to as.POSIXlt("2015-12-04 08:36:12 GMT").
1/1 mismatches
[1] 2015-12-04 09:36:12 - 2015-12-04 08:36:12 == 1 hours
```
I have tried to read in the Jsondatetime string story but this not quite uniformly defined.
If I then check the documentation of ``.convert_JSON_Datetime`` shows that it delivers a POSIXct (POSIX central time) object.  While in the test you are comparing rData (the result) with a POSIXlt (POSIX local time) object. 

In the function.convert_JSON_Datetime  itself I found the following thing:
structure(as.numeric(1449218172199)/1000, class = c("POSIXct", "POSIXt"))
[1] "2015-12-04 09:36:12 CET"

while at my pc the following command failed 
as.POSIXct(1449218172199/1000)
Error in as.POSIXct.numeric(1449218172199/1000) : 
  'origin' must be supplied

When I then look up the origin in the documentation of ``as.POSIX*`{base}

'''
origin : a date-time object, or something which can be coerced by as.POSIXct(tz = "GMT") to such an object.
'''

I am therefore wondering what the correct behavior of .convert_JSON_Datetime should be:
1. Delivering results in GMT --> then the test should not fail, and the function should be changed
2. Delivering time in local system timezone or in my case CET --> then the test is wrong and should be changed accordingly.

please advise

thanks,

Laurens

**Comment by CharlesCara** [comment]
As far as I know DSWS does not return any date & time data, only dates.   

But I think the code should follow the Positct standard and return data in GMT.

**Comment by CharlesCara** [comment]
This is fixed in the latest commit if you want to check on your machine.

**Comment by GreenGrassBlueOcean** [comment]
checked and ok now, thanks!

**Comment by GreenGrassBlueOcean** [comment]
if you add ^.*\.yml$ to .rbuildignore it passes all cran checks now on my pc
