### ISSUE TITLE
issue with NA in a date field

### ISSUE THREAD

**Issue by chenhappy** [CharlesCara/DatastreamDSWS2R#35]
when a mnemonic has NA value for a Date field, it caused error. See below example. Separately each mnemonic returns a value; when we mix one mnemonic that returns NA with another one that returns a non-NA value, the function returns but with the Date in Numeric (that is fine we can convert it to Date late). However when we mix the one mnemonic that have NA value with two mnemonics that have non-NA value, the function failed.
> staticRequest(dwei,DSCode=c("BDUN%TOTQ", "IDUN%TOT",  "MSARGTL")[1],Expression='UPDATE')
  Instrument     UPDATE
1  BDUN%TOTQ 2020-06-03
> staticRequest(dwei,DSCode=c("BDUN%TOTQ", "IDUN%TOT",  "MSARGTL")[2],Expression='UPDATE')
  Instrument     UPDATE
1   IDUN%TOT 2020-04-06
> staticRequest(dwei,DSCode=c("BDUN%TOTQ", "IDUN%TOT",  "MSARGTL")[3],Expression='UPDATE')
  Instrument UPDATE
1    MSARGTL     NA
> staticRequest(dwei,DSCode=c("BDUN%TOTQ", "IDUN%TOT",  "MSARGTL")[2:3],Expression='UPDATE')
  Instrument UPDATE
1   IDUN%TOT  18358
2    MSARGTL     NA
> staticRequest(dwei,DSCode=c("BDUN%TOTQ", "IDUN%TOT",  "MSARGTL")[1:3],Expression='UPDATE')
Error in charToDate(x) : 
  character string is not in a standard unambiguous format

**Comment by CharlesCara** [comment]
I cannot reproduce.  I just get a warning about the NA date but no error:
```
> staticRequest(mydsws,DSCode=c("BDUN%TOTQ", "IDUN%TOT", "MSARGTL")[1:3],Expression='UPDATE')
  Instrument     UPDATE
1  BDUN%TOTQ 2020-06-03
2   IDUN%TOT 2020-04-06
3    MSARGTL       <NA>
Warning message:
In as.POSIXlt.Date(x) : NAs introduced by coercion
```

Could you try upgrading to latest version and check again.
