### ISSUE TITLE
timeSeriesRequest to not convert invalid characters into ".".

### ISSUE THREAD

**Issue by WestWinter1** [CharlesCara/DatastreamDSWS2R#36]
I've asked this question on the [Refinitiv forum](https://community.developers.refinitiv.com/questions/61805/why-does-the-columnnames-reformat-my-brackets-into.html?childToView=61841#answer-61841) and understood that timeSeriesRequest calls the make.name function to create column names.

However, I do find this not useful as I do use the original names (eg XMUJ (NAV)) to find out historical time series of a particular NAV of a security. Is this behavior changeable to allow invalid characters (and spaces)?

Thanks.

**Comment by CharlesCara** [comment]
Not sure how this can be fixed - we need to set the column headings and if there is an invalid character then we will get an error.  
So if there are specific column headings that are needed then these should be set by your code after the xts has been returned by timeSeriesRequest.
