### ISSUE TITLE
Feature request: SEDOL to Mnemonic

### ISSUE THREAD

**Issue by WestWinter1** [CharlesCara/DatastreamDSWS2R#38]
From my current process, I would need to go from entering SEDOL into the eikonapir to retrieve the RIC, which will then be used with the package to retrieve the mnemonic. Is there a way to skip the eikonapir step and have the code recognize a SEDOL string and return the appropriate mnemonic?

The reason why I asked about this is because of the fact that there are some securities which does not have corresponding RICs in Eikon & DSWS. For example, ITA.Z is the primary RIC for the SEDOL B14MG44 in Eikon, while if you search the same SEDOL up in DS, the RIC is ITA instead.

Thanks!

**Comment by CharlesCara** [comment]
I suggest that you contact Refinitiv about data content.  

But you can add UK to the start of a 7 digit SEDOL and use it in DSWS:
```
 mydsws$snapshotRequest(instrument = "UKB14MG44", datatype = "NAME", requestDate = "0D")
  Instrument                               NAME
1  UKB14MG44 ISHARES US AEROSPACE & DEFENSE ETF
```
