### ISSUE TITLE
Client error 403

### ISSUE THREAD

**Issue by awatt43** [CharlesCara/DatastreamDSWS2R#43]
Hi there

I keep getting the following error when trying to access datastream through R. Is this an issue with the package or my DS credentials? 

Thanks
Abigail
![R   DS Error](https://user-images.githubusercontent.com/77967582/134691927-e04079dd-b8ca-4ba5-91da-953311555882.png)

**Comment by CharlesCara** [comment]
The package is working for me.

```
> library(DatastreamDSWS2R)
> mydsws <- dsws$new()
> mydsws$snapshotRequest(instrument = c("ABF","RIO","WPP"),
+                        datatype = "P",
+                        requestDate = "0D")
  Instrument      P
1        ABF 1903.5
2        RIO 4858.0
3        WPP  997.0

```

Is this your first time accessing DSWS or did it work before?  

That message is usually due to invalid username and password.  Can you check that you have the correct credentials.  The correct username is the 'childId' comprising 4 characters and 3 digits. It should not be the 'parentid'.

You can check that you have valid access with [Refinitiv's test DSWS service](https://product.datastream.com/DswsClient/Docs/TestRestV1.aspx).

**Comment by awatt43** [comment]
Hi Charles

Sorry for the slow response. I used to be able to use the package without issue. 

I contacted DS regarding the credentials and they are looking into this. 

I used that test and it seems to return a token so I am unsure of the issue.

![R error with DS](https://user-images.githubusercontent.com/77967582/135045888-be98e643-5e27-4f1e-a3d4-7a3d0e3ad4b0.PNG)

Thanks
Abigail

**Comment by CharlesCara** [comment]
Hi Abigail

This is odd. One possibility is that the session has somehow become stale. Can I suggest clearing all environment variables, restarting R and then seeing if you can download.  

If it is still failing then can you run the request with logging: 
```
mydsws <- DatastreamDSWS2R::dsws$new()
mydsws$logging <- 6
mydsws$snapshotRequest(instrument = c("ABF", "RIO", "WPP"), datatype = "P", requestDate = "0D")

```
Charles

**Comment by awatt43** [comment]
Hi Charles

Tried a few things. I have reset my password, uninstalled & reinstalled the package then followed your suggested steps above.

Still getting the same error, please see the log attached.
![Log for GH](https://user-images.githubusercontent.com/77967582/135065000-41741f56-322f-4fc8-9308-5e3b1d8ad0d5.PNG)

Thanks
Abigail

**Comment by gabrielpulga** [comment]
I'm having the same issue @CharlesCara , @awatt43 

```
Error in .self$.requestToken() : 
 Error requesting access Token.  HTTP message was: Client error : Forbidden : Client error: (403) Forbidden
Calls: <Anonymous> ... initialize -> <Anonymous> -> <Anonymous> -> <Anonymous>
Execution halted
```

This is currently blocking the deployment of my application.

**Comment by CharlesCara** [comment]
@gabrielpulga Your error is occurring at different step to @awatt43 's issue, at the authetication stage.  I would suggest checking your credentials are correct, clearing all environment variables, restarting R and then seeing if you can download. 

If it is still failing then check that you have valid access with Refinitiv's test DSWS service or contact your Refinitiv support representative.

**Comment by awatt43** [comment]
Hi all

To come back on this I have later found out from Refinitv that my access was cutoff due to using up my monthly data allowance. Annoyingly this meant I couldn't even put through a request to send my data usage but after chatting with my sales rep it was confirmed that this was the issue.

Thanks for your help on this Charles!

Abigail

**Comment by CharlesCara** [comment]
@gabrielpulga I have received word from Refinitiv that your error might due to the URL that this package uses.  This has been changed in v1.8.1 which is now available on this repository.
