### ISSUE TITLE
Error requesting json

### ISSUE THREAD

**Issue by gallarati1** [CharlesCara/DatastreamDSWS2R#5]
Hi, I have been using your package without problems until 2 weeks ago. I did not change username or password for Datastream, but this morning, suddenly this error appeared while trying to donwload a time series. How could I solve it? did something change in the function in the package? Thanks!

code: 

mydsws <- dsws$new()
xtsData <- mydsws$timeSeriesRequest(instrument = "MKS",
                                    datatype = "MV",
                                    startDate = "-30D",
                                    endDate = "-0D",
                                    frequency = "D")

Console:

Error requesting json...
Error: Forbidden

GenericCurlError:
Forbidden

ForbiddenHTTPErrorsimpleErrorerrorcondition
Error in rjson::fromJSON(json_str = myDataResponse) : 
  STRING_ELT() can only be applied to a 'character vector', not a 'list'

**Comment by CharlesCara** [comment]
Hi
It looks like the DSWS is sending back a malformed response.  However, that request is working for me.  

Could you run this code and post the output after removing the string after `"TokenValue":` in the first section.

```
mydsws <- dsws$new()
mydsws$setLogging(5L)
xtsData <- mydsws$timeSeriesRequest(instrument = "MKS",
                                    datatype = "MV",
                                    startDate = "-30D",
                                    endDate = "-0D",
                                    frequency = "D")
```

**Comment by gallarati1** [comment]
Hi,
I have contacted Datastream and it seems that the problem was on their side. Now it works.
Thank you for your help!
