### ISSUE TITLE
CRAN? 

### ISSUE THREAD

**Issue by mbannert** [CharlesCara/DatastreamDSWS2R#6]
Do you have any plans to put this on CRAN and give this nice package a little more exposure? 
If you need help with that...  I am in.

**Comment by asrServer** [comment]
Hi Matt

I have never put a package on CRAN, but if you are willing to help this newbie do then it would be good to get more exposure for the package.

Charles

**Comment by mbannert** [comment]
Hi Charles @asrServer , 

sorry it took me a while to get back to you. But hey let's do it. Which workflow would you prefer: 

a) I fork the repo make the changes and you may pull again from my repo

b) You give me collaborator access to this github repo and I make the necessary adjustments and give you feedback so you can continue maintaining the package on your own. Also, in that case I would only issue Pull Requests (PR) and you would accept them and merge to master. 

What do you think? Would be great to start the project!

**Comment by CharlesCara** [comment]
Thanks for the explanation.  I think it would be good to go with the second option, so I will permission you.

**Comment by mbannert** [comment]
ok I added a branch **cran_release** to make the package CRAN ready step-by-step. Basically I am just working through different NOTEs and WARNINGS that different flavors R CMD CHECK return. 

btw.: I've seen we've a dependency (import) on dplyr just because of a single function *bind_cols* . While dplyr is certainly a good package, the fewer dependency the better and I feel like bind_cols may not be super special and it may be easily replaced with some base R.

**Comment by CharlesCara** [comment]
Thank you for doing this.  

We did originally use base R at this point and but found it did not handle different datatypes (particularly dates) and so switched to bind_cols as a quick solution.  We still have the unit tests from that change in test-wrapper-staticListRequestSet.R, so if the new code passes those checks then it should be fine.

**Comment by mbannert** [comment]
Hey just a quick update. I've been abroad (useR!2019) and returned with a busy schedule. However, I am still motivated to do it as the package gains more traction now that the old interface is out of service.

I think we need to use imports instead of :: and a few other things. Are you a Java or Python developer? Or why do you do all the OO? (Don't worries, I am not arguing to change it ;) )

**Comment by asrServer** [comment]
That would have been fun going to Toulouse - hope it was not too hot!

Yes I learnt java before switching to R, and so maybe naturally fell into the OO way of building things.   But there was another motivation.  We use big arrays of downloaded data and I wanted a way of minimising the memory/copying load when applying operations.  

Happy to use @importFrom although Hadley says :: is just as good and can avoid name conflicts. What I do want to avoid is bulk imports of a package namespace - xts and dplyr can clash badly.

**Comment by CharlesCara** [comment]
Package has now been released to CRAN.  Thank you for your help and work doing this.
