### ISSUE TITLE
Usage Stats

### ISSUE THREAD

**Issue by ghost** [CharlesCara/DatastreamDSWS2R#7]
Is it possible to download the usage stats as described in page 2 of the PDF linked below inside of R?  I have tried the following, but could not get back a valid response:

mydsws$snapshotRequest(instrument = "STATS", datatype = "DS.USERSTATS", requestDate = "0D")

https://developers.refinitiv.com/sites/default/files/DSWS%20for%20Desktop%20-%20User%20stats%20and%20limits_0.pdf

**Comment by CharlesCara** [comment]
DSWS returns the usage statistics in a different format to the other data, so this will require an enhancement.

**Comment by CharlesCara** [comment]
This enhancement has been added in version 1.6.1.  Please note that requestDate has to be an actual date and not a relative date.  Please see examples in documentation
