### ISSUE TITLE
RIC codes with lower case letters are converted to uppercase

### ISSUE THREAD

**Issue by ghost** [CharlesCara/DatastreamDSWS2R#8]
For example: <WAFGn.DE>:

JSON request to DSWS server is:

{"DataRequest":{"DataTypes":[{"Properties":{},"Value":["ISIN"]},{"Properties":{},"Value":["MED#(X(VA)~U$, -1Y, 0D)"]}],"Date":{"End":["2019-06-07"],"Frequency":["D"],"Kind":[0],"Start":["2019-06-07"]},"Instrument":{"Properties":{},"Value":["<WAFGN.DE>"]},"Tag":{}},"Properties":{"Properties":{}},"TokenValue":["xxx"]}

**Comment by CharlesCara** [comment]
I did not know that RICs were case sensitive. I have removed the forcing of instruments into upper case, so if you pull the most recent release then this should be working for you
